### ISSUE TITLE
use latest testsuite

### ISSUE THREAD

**Issue by willnorris** [dissolve/mf2-tester#3]
I looks like the [mf2/tests package](https://packagist.org/packages/mf2/tests) was last updated in March.  How would you feel about doing a git checkout of the latest testsuite during `initialize.sh` instead of loader the composer package?

Alternately, we could have someone setup the packagist GitHub webhook to auto-push to packagist on each commit.  Reading through https://github.com/composer/packagist/issues/907, it looks like they're actively trying to move that over to a GitHub App, but we should still be able to install it as a service for the next month or two before they turn that off.

**Comment by dissolve** [comment]
It's supposed to use "prefer source" which should install from GitHub.  But
then updating is basically done by running a git pull in the
vendor/mf2/tests directory.  Could use a submodule, I suppose that would be
fine, I usually sit away from them though as I have had issues in the past

**Comment by willnorris** [comment]
ah, yeah... composer is indeed pulling down the git repo, just at an older commit.  I wasn't sure if you were manually updating the tests or not on your end.

Agreed on submodules often causing issues.  I do use them for the go parser, and like being able to checkin the update to a more recent version of the tests in the same commit as the update to the parser.  So far, I haven't done anything exotic, so submodules have been fine, but I've definitely had problems in the past as well.
